[profile.default]
src = "src"  # Source directory for your contracts
out = "out"  # Output directory for build artifacts
libs = ["lib"]  # Libraries directory for dependencies

# Solidity compiler settings
solc-version = "0.8.17"  # Use Solidity version 0.8.17

# Optimization settings
optimizer = true         # Enable the optimizer
optimizer-runs = 200     # Number of optimization runs
